# Autogenerated wrapper script for XGBoost_jll for x86_64-w64-mingw32
export libxgboost, xgboost

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("XGBoost")
JLLWrappers.@declare_library_product(libxgboost, "xgboost.dll")
JLLWrappers.@declare_executable_product(xgboost)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libxgboost,
        "bin\\xgboost.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        xgboost,
        "bin\\xgboost.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
